name: on-push-workflow
on: push

env:
  CI: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run test
        run: make ci

  push-docker-image:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: vladislavmel/devops-for-programmers-project-74:latest